#%RAML 0.8
title: Holonic MES API
version: v1
#baseUri: http://mes.io/wms/api/{version}
baseUri: http://127.0.0.1:5000
mediaType: application/json
documentation:
  - title: Holonic MES API
    content: ""
  - title: Use cases
    content: |
      Show the manufacturing capacity
  - title: Manufacturing Execution System
    content: |
      FIXME
