#%RAML 0.8
title: Holonic MES API
version: v1
#baseUri: http://mes.io/mes/api/{version}
baseUri: http://127.0.0.1:5000
mediaType: application/json
documentation:
  - title: Holonic MES API
    content: ""
  - title: Use cases
    content: |
      Show the manufacturing capacity
  - title: Manufacturing Execution System
    content: |
      Personnel Capability
      Material Capability
      Equipment Segment Capability
      Personnel Segment Specification
      Material Segment Specification
      Equipment Specification
      Personnel Requirement
      Material Produced Requirement
      Consumable Expected
      Equipment Actual
      Material Consumed Actual
      Equipment Capability
      Personnel Segment Capability
      Material Segment Capability
      Equipment Segment Specification
      Personnel Specification
      Material Specification
      Equipment Requirement
      Material Consumed Requirement
      Personnel Actual
      Material Produced Actual
      Consumable Actual

schemas:
  - Product: !include json/commons-material-schema.json
  - Products: !include json/commons-materials-schema.json
  - Material: !include json/commons-material-schema.json
  - Materials: !include json/commons-materials-schema.json
  - Component: !include json/commons-material-schema.json
  - Components: !include json/commons-materials-schema.json
  - Inventory: !include json/commons-material-schema.json
  - Inventories: !include json/commons-materials-schema.json
  - Equipment: !include json/commons-material-schema.json
  - Equipments: !include json/commons-materials-schema.json
  - Tooling: !include json/commons-material-schema.json
  - Toolings: !include json/commons-materials-schema.json
  - Personnel: !include json/manufacturing-fsmt-schema.json
  - Person: !include json/manufacturing-fsmt-schema.json
  - Process: !include json/manufacturing-fsmt-schema.json
  - Processes: !include json/manufacturing-fsmt-schema.json
  - Operation: !include json/manufacturing-operation-document-schema.json
  - Operations: !include json/manufacturing-operation-documents-schema.json
  - FSMT: !include json/manufacturing-fsmt-schema.json
  - EBOM: !include json/manufacturing-bom-document-schema.json
  - EBOMs: !include json/manufacturing-bom-documents-schema.json
  - MBOM: !include json/manufacturing-bom-document-schema.json
  - MBOMs: !include json/manufacturing-bom-documents-schema.json
  - Error: !include json/commons-error-schema.json
  - Message: !include json/commons-message-schema.json


/materials:
  get:
    description: Get a list of Materials
    responses:
      200:
        body:
          application/json:
            schema: Materials
  post:
    description: Add new Material
    body:
      application/json:
        schema: Material
    responses:
      201:
        body:
          application/json:
            schema: Material
  /{resourceId}:
    get:
      description: Get a Material by ID
      responses:
        200:
          body:
            application/json:
              schema: Material
        404:
          body:
            application/json:
              schema: Error
    put:
      description: Update Material by ID
      body:
        application/json:
          schema: Material
      responses:
        200:
          body:
            application/json:
              schema: Material
        404:
          body:
            application/json:
              schema: Error
    delete:
      description: Delete a Material by ID
      responses:
        204:
        404:
          body:
            application/json:
              schema: Error

/components:
  get:
    description: Get a list of Components
    responses:
      200:
        body:
          application/json:
            schema: Components
  post:
    description: Add new Component
    body:
      application/json:
        schema: Component
    responses:
      201:
        body:
          application/json:
            schema: Component
  /{resourceId}:
    get:
      description: Get a Component by ID
      responses:
        200:
          body:
            application/json:
              schema: Component
        404:
          body:
            application/json:
              schema: Error
    put:
      description: Update Component by ID
      body:
        application/json:
          schema: Component
      responses:
        200:
          body:
            application/json:
              schema: Component
        404:
          body:
            application/json:
              schema: Error
    delete:
      description: Delete a Component by ID
      responses:
        204:
        404:
          body:
            application/json:
              schema: Error

/inventories:
  get:
    description: Get a list of Inventories
    responses:
      200:
        body:
          application/json:
            schema: Inventories
  post:
    description: Add new Inventory
    body:
      application/json:
        schema: Inventory
    responses:
      201:
        body:
          application/json:
            schema: Inventory
  /{resourceId}:
    get:
      description: Get a Inventory by ID
      responses:
        200:
          body:
            application/json:
              schema: Inventory
        404:
          body:
            application/json:
              schema: Error
    put:
      description: Update Inventory by ID
      body:
        application/json:
          schema: Inventory
      responses:
        200:
          body:
            application/json:
              schema: Inventory
        404:
          body:
            application/json:
              schema: Error
    delete:
      description: Delete a Inventory by ID
      responses:
        204:
        404:
          body:
            application/json:
              schema: Error

/equipments:
  get:
    description: Get a list of Equipments
    responses:
      200:
        body:
          application/json:
            schema: Equipments
  post:
    description: Add new Equipment
    body:
      application/json:
        schema: Equipment
    responses:
      201:
        body:
          application/json:
            schema: Equipment
  /{resourceId}:
    get:
      description: Get a Equipment by ID
      responses:
        200:
          body:
            application/json:
              schema: Equipment
        404:
          body:
            application/json:
              schema: Error
    put:
      description: Update Equipment by ID
      body:
        application/json:
          schema: Equipment
      responses:
        200:
          body:
            application/json:
              schema: Equipment
        404:
          body:
            application/json:
              schema: Error
    delete:
      description: Delete a Equipment by ID
      responses:
        204:
        404:
          body:
            application/json:
              schema: Error

/toolings:
  get:
    description: Get a list of Toolings
    responses:
      200:
        body:
          application/json:
            schema: Toolings
  post:
    description: Add new Tooling
    body:
      application/json:
        schema: Tooling
    responses:
      201:
        body:
          application/json:
            schema: Tooling
  /{resourceId}:
    get:
      description: Get a Tooling by ID
      responses:
        200:
          body:
            application/json:
              schema: Tooling
        404:
          body:
            application/json:
              schema: Error
    put:
      description: Update Tooling by ID
      body:
        application/json:
          schema: Tooling
      responses:
        200:
          body:
            application/json:
              schema: Tooling
        404:
          body:
            application/json:
              schema: Error
    delete:
      description: Delete a Tooling by ID
      responses:
        204:
        404:
          body:
            application/json:
              schema: Error

/personnel:
  get:
    description: Get a list of Persons
    responses:
      200:
        body:
          application/json:
            schema: Personnel
  post:
    description: Add new Person
    body:
      application/json:
        schema: Person
    responses:
      201:
        body:
          application/json:
            schema: Person
  /{resourceId}:
    get:
      description: Get a Person by ID
      responses:
        200:
          body:
            application/json:
              schema: Person
        404:
          body:
            application/json:
              schema: Error
    put:
      description: Update Person by ID
      body:
        application/json:
          schema: Person
      responses:
        200:
          body:
            application/json:
              schema: Person
        404:
          body:
            application/json:
              schema: Error
    delete:
      description: Delete a Person by ID
      responses:
        204:
        404:
          body:
            application/json:
              schema: Error


/products:
  get:
    description: Get a list of Products
    responses:
      200:
        body:
          application/json:
            schema: Products
  post:
    description: Add new Product
    body:
      application/json:
        schema: Product
    responses:
      201:
        body:
          application/json:
            schema: Product
  /{resourceId}:
    get:
      description: Get a Product by ID
      responses:
        200:
          body:
            application/json:
              schema: Product
        404:
          body:
            application/json:
              schema: Error
    put:
      description: Update Product by ID
      body:
        application/json:
          schema: Product
      responses:
        200:
          body:
            application/json:
              schema: Product
        404:
          body:
            application/json:
              schema: Error
    delete:
      description: Delete a Product by ID
      responses:
        204:
        404:
          body:
            application/json:
              schema: Error

/production:
  get:
  post:
  /{resourceId}:
    get:
    delete:
    /definition:
      patch:
    /fsmt:
      put:

/process:
  get:
  post:
  /{resourceId}:
    get:
    delete:
    /definition:
      patch:
    /fsmt:
      put:

/request:
  get:
  post:
  /{resourceId}:
    get:
    delete:
    /definition:
      patch:
    /fsmt:
      put:

/response:
  get:
  post:
  /{resourceId}:
    get:
    delete:
    /definition:
      patch:
    /fsmt:
      put:

/operations:
  description: |
    An operation card (KTP)
  get:
    description: Get a list of Operation cards
    queryParameters:
      sdate:
        displayName: Start Date
        type: date
        description: Start date
        example: 2017-01-01
        required: false
        default: 2017-01-01
      edate:
        displayName: End Date
        type: date
        description: End date
        example: 2017-01-01
        required: false
        default: 2017-01-10
      hierarhy:
        displayName: Hierarhy
        type: string
        description: Hierarhy scope
        example: SITE
        required: false
        default: SITE
    responses:
      200:
        body:
          application/json:
            schema: Operations
            example: !include ./json/manufacturing-operation-documents-example.json
  post:
    description: Add new Operation card
    body:
      application/json:
        schema: Operation
        example: !include ./json/manufacturing-operation-document-example.json
    responses:
      201:
        body:
          application/json:
            schema: Message
            example: !include ./json/commons-message-example.json
      400:
        body:
            application/json:
              schema: Error
              example: !include ./json/commons-error-example.json
  /{resourceId}:
    get:
      description: Get a Operation Card by ID
      responses:
        200:
          body:
            application/json:
              schema: Operation
              example: !include ./json/manufacturing-operation-document-example.json
        404:
          body:
            application/json:
              schema: Error
              example: !include ./json/commons-error-example.json
    delete:
      description: Delete a Operation Card by ID
      responses:
        204:
        404:
          body:
            application/json:
              schema: Error
              example: !include ./json/commons-error-example.json
    /definition:
      patch:
        description: Reinit definition
        body:
          application/json:
            schema: Operation
            example: !include ./json/manufacturing-operation-document-example.json
        responses:
          200:
            body:
              application/json:
                schema: Message
                example: !include ./json/commons-message-example.json
          400:
            body:
              application/json:
                schema: Error
                example: !include ./json/commons-error-example.json
      /personnel:
        patch:
          description: Reinit personnel definition
          responses:
            501:
      /toolings:
        patch:
          description: Reinit toolings definition
          responses:
            501:
      /materials:
        patch:
          description: Reinit material definition
          responses:
            501:
    /fsmt:
      put:
        body:
          application/json:
            schema: FSMT
            example: !include ./json/manufacturing-fsmt-example.json
        responses:
          200:
            body:
              application/json:
                schema: Message
                example: !include ./json/commons-message-example.json
          404:
            body:
              application/json:
                schema: Error
                example: !include ./json/commons-error-example.json

/ebom:
  description: |
    An engeneering bill of material
  get:
    description: Get a list of EBOMs
    queryParameters:
      sdate:
        displayName: Start Date
        type: date
        description: Start date
        example: 2017-01-01
        required: false
        default: 2017-01-01
      edate:
        displayName: End Date
        type: date
        description: End date
        example: 2017-01-01
        required: false
        default: 2017-01-10
      hierarhy:
        displayName: Hierarhy
        type: string
        description: Hierarhy scope
        example: SITE
        required: false
        default: SITE
    responses:
      200:
        body:
          application/json:
            schema: EBOMs
            example: !include ./json/manufacturing-bom-documents-example.json
  post:
    description: Add new EBOM
    body:
      application/json:
        schema: EBOM
        example: !include ./json/manufacturing-bom-document-example.json
    responses:
      201:
        body:
          application/json:
            schema: Message
            example: !include ./json/commons-message-example.json
      400:
        body:
            application/json:
              schema: Error
              example: !include ./json/commons-error-example.json
  /{resourceId}:
    get:
      description: Get a EBOM by ID
      responses:
        200:
          body:
            application/json:
              schema: EBOM
              example: !include ./json/manufacturing-bom-document-example.json
        404:
          body:
            application/json:
              schema: Error
              example: !include ./json/commons-error-example.json
    delete:
      description: Delete a EBOM by ID
      responses:
        204:
        404:
          body:
            application/json:
              schema: Error
              example: !include ./json/commons-error-example.json
    /definition:
      patch:
        description: Reinit definition
        body:
          application/json:
            schema: EBOM
            example: !include ./json/manufacturing-bom-document-example.json
        responses:
          200:
            body:
              application/json:
                schema: Message
                example: !include ./json/commons-message-example.json
          400:
            body:
              application/json:
                schema: Error
                example: !include ./json/commons-error-example.json
    /fsmt:
      put:
        body:
          application/json:
            schema: FSMT
            example: !include ./json/manufacturing-fsmt-example.json
        responses:
          200:
            body:
              application/json:
                schema: Message
                example: !include ./json/commons-message-example.json
          404:
            body:
              application/json:
                schema: Error
                example: !include ./json/commons-error-example.json

/mbom:
  description: |
    A manufacturing bill of material
  get:
    description: Get a list of MBOMs
    queryParameters:
      sdate:
        displayName: Start Date
        type: date
        description: Start date
        example: 2017-01-01
        required: false
        default: 2017-01-01
      edate:
        displayName: End Date
        type: date
        description: End date
        example: 2017-01-01
        required: false
        default: 2017-01-10
      hierarhy:
        displayName: Hierarhy
        type: string
        description: Hierarhy scope
        example: SITE
        required: false
        default: SITE
    responses:
      200:
        body:
          application/json:
            schema: MBOMs
            example: !include ./json/manufacturing-bom-documents-example.json
  post:
    description: Add new MBOM
    body:
      application/json:
        schema: MBOM
        example: !include ./json/manufacturing-bom-document-example.json
    responses:
      201:
        body:
          application/json:
            schema: Message
            example: !include ./json/commons-message-example.json
      400:
        body:
            application/json:
              schema: Error
              example: !include ./json/commons-error-example.json
  /{resourceId}:
    get:
      description: Get a MBOM by ID
      responses:
        200:
          body:
            application/json:
              schema: MBOM
              example: !include ./json/manufacturing-bom-document-example.json
        404:
          body:
            application/json:
              schema: Error
              example: !include ./json/commons-error-example.json
    delete:
      description: Delete a MBOM by ID
      responses:
        204:
        404:
          body:
            application/json:
              schema: Error
              example: !include ./json/commons-error-example.json
    /definition:
      patch:
        description: Reinit definition
        body:
          application/json:
            schema: MBOM
            example: !include ./json/manufacturing-bom-document-example.json
        responses:
          200:
            body:
              application/json:
                schema: Message
                example: !include ./json/commons-message-example.json
          400:
            body:
              application/json:
                schema: Error
                example: !include ./json/commons-error-example.json
    /fsmt:
      put:
        body:
          application/json:
            schema: FSMT
            example: !include ./json/manufacturing-fsmt-example.json
        responses:
          200:
            body:
              application/json:
                schema: Message
                example: !include ./json/commons-message-example.json
          404:
            body:
              application/json:
                schema: Error
                example: !include ./json/commons-error-example.json
