#%RAML 0.8
title: Holonic MES API
version: v1
#baseUri: http://mes.io/mes/api/{version}
baseUri: http://127.0.0.1:5000
mediaType: application/json
documentation:
  - title: Holonic MES API
    content: ""
  - title: Use cases
    content: |
      Show the manufacturing capacity
  - title: Manufacturing Execution System
    content: |
      Personnel Capability
      Material Capability
      Equipment Segment Capability
      Personnel Segment Specification
      Material Segment Specification
      Equipment Specification
      Personnel Requirement
      Material Produced Requirement
      Consumable Expected
      Equipment Actual
      Material Consumed Actual
      Equipment Capability
      Personnel Segment Capability
      Material Segment Capability
      Equipment Segment Specification
      Personnel Specification
      Material Specification
      Equipment Requirement
      Material Consumed Requirement
      Personnel Actual
      Material Produced Actual
      Consumable Actual

schemas:
  - Product: !include json/manufacturing-fsmt-schema.json
  - Products: !include json/manufacturing-fsmt-schema.json
  - Material: !include json/manufacturing-fsmt-schema.json
  - MaterialItem: !include json/manufacturing-fsmt-schema.json
  - Component: !include json/manufacturing-fsmt-schema.json
  - ComponentItem: !include json/manufacturing-fsmt-schema.json
  - Inventory: !include json/manufacturing-fsmt-schema.json
  - InventoryItem: !include json/manufacturing-fsmt-schema.json
  - Equipment: !include json/manufacturing-fsmt-schema.json
  - EquipmentItem: !include json/manufacturing-fsmt-schema.json
  - Tooling: !include json/manufacturing-fsmt-schema.json
  - ToolingItem: !include json/manufacturing-fsmt-schema.json
  - Personnel: !include json/manufacturing-fsmt-schema.json
  - Person: !include json/manufacturing-fsmt-schema.json
  - Process: !include json/manufacturing-fsmt-schema.json
  - Processes: !include json/manufacturing-fsmt-schema.json
  - FSMT: !include json/manufacturing-fsmt-schema.json
  - EBOM: !include json/manufacturing-bom-document-schema.json
  - EBOMs: !include json/manufacturing-bom-documents-schema.json
  - MBOM: !include json/manufacturing-bom-document-schema.json
  - MBOMs: !include json/manufacturing-bom-documents-schema.json
  - Error: !include json/commons-error-schema.json
  - Message: !include json/commons-message-schema.json


/material:
/component:
/inventory:
/equipment:
/tooling:
/personnel:
/product:

/production:
  get:
  post:
  /{resourceId}:
    get:
    delete:
    /definition:
      patch:
    /fsmt:
      put:

/process:
  get:
  post:
  /{resourceId}:
    get:
    delete:
    /definition:
      patch:
    /fsmt:
      put:

/request:
  get:
  post:
  /{resourceId}:
    get:
    delete:
    /definition:
      patch:
    /fsmt:
      put:

/response:
  get:
  post:
  /{resourceId}:
    get:
    delete:
    /definition:
      patch:
    /fsmt:
      put:

/operation:
  get:
  post:
  /{resourceId}:
    get:
    delete:
    /definition:
      patch:
    /fsmt:
      put:

/ebom:
  description: |
    An engeneering bill of material
  get:
    description: Get a list of EBOMs
    queryParameters:
      sdate:
        displayName: Start Date
        type: date
        description: Start date
        example: 2017-01-01
        required: false
        default: 2017-01-01
      edate:
        displayName: End Date
        type: date
        description: End date
        example: 2017-01-01
        required: false
        default: 2017-01-10
      hierarhy:
        displayName: Hierarhy
        type: string
        description: Hierarhy scope
        example: SITE
        required: false
        default: SITE
    responses:
      200:
        body:
          application/json:
            schema: EBOMs
            example: !include ./json/manufacturing-bom-documents-example.json
  post:
    description: Add new EBOM
    body:
      application/json:
        schema: EBOM
        example: !include ./json/manufacturing-bom-document-example.json
    responses:
      201:
        body:
          application/json:
            schema: Message
            example: !include ./json/commons-message-example.json
      400:
        body:
            application/json:
              schema: Error
              example: !include ./json/commons-error-example.json
  /{resourceId}:
    get:
      description: Get a EBOM by ID
      responses:
        200:
          body:
            application/json:
              schema: EBOM
              example: !include ./json/manufacturing-bom-document-example.json
        404:
          body:
            application/json:
              schema: Error
              example: !include ./json/commons-error-example.json
    delete:
      description: Delete a EBOM by ID
      responses:
        204:
        404:
          body:
            application/json:
              schema: Error
              example: !include ./json/commons-error-example.json
    /definition:
      patch:
        description: Reinit definition
        body:
          application/json:
            schema: EBOM
            example: !include ./json/manufacturing-bom-document-example.json
        responses:
          200:
            body:
              application/json:
                schema: Message
                example: !include ./json/commons-message-example.json
          400:
            body:
              application/json:
                schema: Error
                example: !include ./json/commons-error-example.json
    /fsmt:
      put:
        body:
          application/json:
            schema: FSMT
            example: !include ./json/manufacturing-fsmt-example.json
        responses:
          200:
            body:
              application/json:
                schema: Message
                example: !include ./json/commons-message-example.json
          404:
            body:
              application/json:
                schema: Error
                example: !include ./json/commons-error-example.json

/mbom:
  description: |
    A manufacturing bill of material
  get:
    description: Get a list of MBOMs
    queryParameters:
      sdate:
        displayName: Start Date
        type: date
        description: Start date
        example: 2017-01-01
        required: false
        default: 2017-01-01
      edate:
        displayName: End Date
        type: date
        description: End date
        example: 2017-01-01
        required: false
        default: 2017-01-10
      hierarhy:
        displayName: Hierarhy
        type: string
        description: Hierarhy scope
        example: SITE
        required: false
        default: SITE
    responses:
      200:
        body:
          application/json:
            schema: MBOMs
            example: !include ./json/manufacturing-bom-documents-example.json
  post:
    description: Add new MBOM
    body:
      application/json:
        schema: MBOM
        example: !include ./json/manufacturing-bom-document-example.json
    responses:
      201:
        body:
          application/json:
            schema: Message
            example: !include ./json/commons-message-example.json
      400:
        body:
            application/json:
              schema: Error
              example: !include ./json/commons-error-example.json
  /{resourceId}:
    get:
      description: Get a MBOM by ID
      responses:
        200:
          body:
            application/json:
              schema: MBOM
              example: !include ./json/manufacturing-bom-document-example.json
        404:
          body:
            application/json:
              schema: Error
              example: !include ./json/commons-error-example.json
    delete:
      description: Delete a MBOM by ID
      responses:
        204:
        404:
          body:
            application/json:
              schema: Error
              example: !include ./json/commons-error-example.json
    /definition:
      patch:
        description: Reinit definition
        body:
          application/json:
            schema: MBOM
            example: !include ./json/manufacturing-bom-document-example.json
        responses:
          200:
            body:
              application/json:
                schema: Message
                example: !include ./json/commons-message-example.json
          400:
            body:
              application/json:
                schema: Error
                example: !include ./json/commons-error-example.json
    /fsmt:
      put:
        body:
          application/json:
            schema: FSMT
            example: !include ./json/manufacturing-fsmt-example.json
        responses:
          200:
            body:
              application/json:
                schema: Message
                example: !include ./json/commons-message-example.json
          404:
            body:
              application/json:
                schema: Error
                example: !include ./json/commons-error-example.json
